-- Active: 1698768500977@@127.0.0.1@3306@Assignment6
#Task 3

#Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.

#here Both products table and order_items table have price/ unit price, I am considering  unit_price * quantity as total_revenue
SELECT c.name as category_name, SUM(oi.quantity *  oi.unit_price) AS total_revenue
FROM categories AS c
LEFT JOIN products AS p ON c.id = p.category_id
LEFT JOIN order_items AS oi ON p.id = oi.product_id
GROUP BY c.name
ORDER BY total_revenue DESC;